apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: crd-tiller-role
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  - extensions
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: sealed-secret-user-role
rules:
- apiGroups:
  - ''
  resources:
  - services/proxy
  verbs:
  - 'get'
