{{- range .Values.projects -}}
{{- $project := . -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $project.name }}-security-rolebinding
  namespace: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secret-user-role
subjects:
{{ index $project "users" | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $project.name }}-rolebinding
  namespace: {{ $project.tiller }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
{{- if $project.tiller }}
  - kind: ServiceAccount
    name: {{ $project.tiller }}
    namespace: {{ $project.tiller }}
{{- end }}
{{ index $project "users" | indent 2 }}
---
{{- range $project.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $project.name }}-admin-rolebinding
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
{{- if $project.tiller }}
  - kind: ServiceAccount
    name: {{ $project.tiller }}
    namespace: {{ $project.tiller }}
{{- end }}
{{ index $project "users" | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $project.name }}-crd-rolebinding
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-tiller-role
subjects:
{{- if $project.tiller }}
  - kind: ServiceAccount
    name: {{ $project.tiller }}
    namespace: {{ $project.tiller }}
{{- end }}
{{ index $project "users" | indent 2 }}
---
{{- end }}
{{- end }}